baseurl = "https://lreed.net/"
languageCode = "en-us"
title = "Luke Reed"
theme = "hugo-orbit-theme"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-5.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Luke Reed"
        tagline = "SRE/Backend Dev"
        avatar = "profile.jpeg"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: luke@lreed.net"
        title = "luke@lreed.net"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/luke-reed-0125"
        title = "linkedin.com/in/luke-reed-0125"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/lucasreed"
        title = "github.com/lucasreed"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "BSc Information & Computer Technology"
        college = "East Carolina University"
        dates = "2007 - 2010"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Native"

    # Interests section
    [params.interests]
        enable = false
        title = "Interests"

        [[params.interests.list]]
        interest = "Climbing"

        [[params.interests.list]]
        interest = "Snowboarding"

        [[params.interests.list]]
        interest = "Cooking"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "As an operations-focused engineer, Luke has the ability and desire to automate everything he can. Passionate about Kubernetes and helping others utilize it to its fullest. Open source work (mostly using Go) can be seen on [Github](https://github.com/lucasreed)."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Senior Devops Engineer"
        dates = "May 2022 - Present"
        company = "Epic Games - Cary, NC"
        details = "Supporting development teams across the organization in keeping their application code and lifecycle running smoothly. This can manifest itself in many ways: Setting up an internal HTTP caching solution, better efficiency/cost savings in our Kubernetes clusters, and developing internal tooling to solve specific issues."

        [[params.jobs.list]]
        position = "Site Reliability Engineering Tech Lead"
        dates = "March 2020 - April 2022"
        company = "Fairwinds - Remote"
        details = "Develop and collaborate on internal and open source tooling to ease the toil of operating Kubernetes clusters."

        [[params.jobs.list]]
        position = "Site Reliability Engineer"
        dates = "June 2019 - March 2020"
        company = "Fairwinds - Remote"
        details = "Operating and Administering production level Kubernetes clusters so you don't have to! A mix of developing internal and open source tooling in golang, cluster maintenance/upgrades, CI/CD implementation, and generally guiding our clients on their journey with Kubernetes in various cloud environments."

        [[params.jobs.list]]
        position = "Systems Engineer"
        dates = "June 2014 - June 2019"
        company = "TiVo (Digitalsmiths) - Durham, NC"
        details = "Support and engineer system solutions in a DevOps environment. Provide on-call support outside of business hours as well as day to day support for both internal and external stakeholders.Support"

        [[params.jobs.list]]
        position = "Senior Unix/Linux Admin"
        dates = "August 2013 - June 2014"
        company = "Credit Suisse - Morrisville, NC"
        details = "Responsible for supporting production, disaster recovery, testing, and development servers for users across the globe. This position involves supporting servers in the EMEA region while being based out of the US. Provided second level escalation break-fix support for EMEA region as well."

        [[params.jobs.list]]
        position = "Unix/Linux Admin"
        dates = "July 2010 - August 2013"
        company = "Credit Suisse - Morrisville, NC"
        details = "Provide global breakfix support for Unix/Linux servers. Unix hosts are a mix of Solaris 8 and 10, some of which were virtual LDOMs or zones."

    # Projects section
    [params.projects]
        enable = false
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "Hugrid"
        url = "https://github.com/aerohub/hugrid"
        tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

    # Skills section
    [params.skills]
        enable = false

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    #
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Luke Reed"
